### ISSUE TITLE
lighttpd doesn't start due to non-existent directory

### ISSUE THREAD

**Issue by stolowski** [tsunghanliu/adsb-box.snap#1]
The lighttpd service silently fails and doesn't listen on 8080 due to (journalctl log):

May 22 21:39:10 localhost.localdomain adsb-box.lighttpd[4636]: /snap/adsb-box/81/bin/lighttpd: 30: /snap/adsb-box/81/bin/lighttpd: cannot create /var/snap/adsb-box/81/lighttpd/lighttpd.conf: Directory nonexistent
May 22 21:39:10 localhost.localdomain adsb-box.lighttpd[4636]: /snap/adsb-box/81/bin/lighttpd: 107: /snap/adsb-box/81/bin/lighttpd: cannot create /var/snap/adsb-box/81/lighttpd/lighttpd.conf: Directory nonexistent
May 22 21:39:10 localhost.localdomain adsb-box.lighttpd[4636]: chmod: cannot access '/var/snap/adsb-box/81/lighttpd/lighttpd.conf': No such file or directory
May 22 21:39:10 localhost.localdomain adsb-box.lighttpd[4636]: 2019-05-22 21:39:10: (configfile.c.1003) opening configfile  /var/snap/adsb-box/81/lighttpd/lighttpd.conf failed: No such file or directory
May 22 21:39:10 localhost.localdomain systemd[1]: snap.adsb-box.lighttpd.service: Main process exited, code=exited, status=255/n/a
May 22 21:39:10 localhost.localdomain systemd[1]: snap.adsb-box.lighttpd.service: Unit entered failed state.
May 22 21:39:10 localhost.localdomain systemd[1]: snap.adsb-box.lighttpd.service: Failed with result 'exit-code'.
May 22 21:39:10 localhost.localdomain systemd[1]: snap.adsb-box.lighttpd.service: Service hold-off time over, scheduling restart.
May 22 21:39:10 localhost.localdomain systemd[1]: Stopped Service for snap application adsb-box.lighttpd.
May 22 21:39:10 localhost.localdomain systemd[1]: snap.adsb-box.lighttpd.service: Start request repeated too quickly.
May 22 21:39:10 localhost.localdomain systemd[1]: Failed to start Service for snap application adsb-box.lighttpd.

After I manually created  /var/snap/adsb-box/current/lighttpd and restarted the service, it started working. The version of adsb-box snap is 1.2.

**Comment by tsunghanliu** [comment]
@stolowski 
Thanks for the report. This issue is now fixed by tsunghanliu/adsb-box.snap@d3d11003817a54ecdabfaf5a8cbef9d3869a307e
I'll release a new version later.
