### ISSUE TITLE
missing rbfeeder?

### ISSUE THREAD

**Issue by dlasher** [tsunghanliu/adsb-box.snap#14]
pi3b+, ubuntu-core - Current version appears to be missing rbfeeder?

`user@localhost:~$ snap services adsb-box.rbfeeder
error: snap "adsb-box" has no service "rbfeeder"
user@localhost:~$ adsb-box.rbfeedercli --showkey
-bash: adsb-box.rbfeedercli: command not found`

everything else appears present?

**Comment by tsunghanliu** [comment]
Hi @dlasher 

As of now, RadarBox feeder is only available on the edge channel.
Which channel are you currently using?

**Comment by dlasher** [comment]
Apologies that wasn't clear. Will give Edge a shot.

**Comment by dlasher** [comment]
Works well on edge, thanks for the note, might want to add something to the readme.

**Comment by tsunghanliu** [comment]
I've released a new version, so it's now aligned with the readme.
