### ISSUE TITLE
Graphs "broken"

### ISSUE THREAD

**Issue by dlasher** [tsunghanliu/adsb-box.snap#16]
repeated this a couple of times with a fresh machine, suspect I can find the answer, just don't know where to look in Snap world.

Fresh install - using Edge (197) , pi3b+, ubuntu 18 lts, "performance" graphs are all broken links, even after rebooting box, restarting services, images on the page are all 404'd.

Where do I look for logs/errors?

```
ubuntu@ubuntu:~$ snap list
Name      Version            Rev   Tracking  Publisher   Notes
adsb-box  v1.2.1-8-g59000a9  197   edge      robertliu   -
core      16-2.42.1          8043  stable    canonical✓  core
```

**Comment by tsunghanliu** [comment]
Hi @dlasher 
Which image are you using? According to the revision, 197 is for arm64 architecture. Recently there is an issue (#13) reported. But, I'm not sure if they are relevant.
For the log, you can use `snap logs adsb-box[.SERVICE]` to get the log and `snap services adsb-box` can list all services of adsb-box..

**Comment by dlasher** [comment]
refreshed edge, graphs all working now. :)
