### ISSUE TITLE
THANKS and a question

### ISSUE THREAD

**Issue by feetsdr** [tsunghanliu/adsb-box.snap#35]
I have been looking to set up an ADS-B feeder. I know windows and have a bunch of retired i5 PCs (still quite functional machines).  Seemed everyone said I need to buy a Pi to do a feeder.

Someone in a tech forum turned me on to 

https://snapcraft.io/install/adsb-box/ubuntu

As a way not to have to buy a Pi which led me to this page.

THANK YOU FOR DOING THIS!!

On Friday night I set up an old PC on ubuntu, installed this and started feeding several sites.

I still have a couple sites that don't seem to be be getting my data.  And the github page above has some steps, but i have questions.

I've never been to github.  Is this issues area where people can post questions about configuring things / get help setting things up?

If not, where on the web would you recommend going for support?  And or more step-by-step procedures to set things up?   Can you tell if lots of people are using this snap?

An example of my situation - I know ipconfig in windows.  In the github page at one point, it says to go to http://your-device-ip:30053/    I didn't know how to get my ip address on a linux box.  Googled that ifconfig -a  ?!   got going to that web page.  Just a funny detour.

Some questions partly about this snap, partly about feeding:

1) The processor in this PC is an i5.  But I installed / could only find an AMD64 iso?  And it worked?

2) What websites is this is setup to feed?
I think:
Flightaware  (working)
FlightRadar24 (working)
PlaneFinder (this one isn't getting data into the app itself - see below #5)
Radarbox ( this one has errors in terminal - see below #7)
ADSBExchange (working)
OpenSky (started setting this one up.  But it wants port forwarding to get into the feeder? Gotta set up the rule in my firewall).

Any others that this snaps ready to talk to? I might as well make sure everyone gets my data?  

Any list of sites and perks you get for feeding?  ADSBExchange doesn't even take the ad off their public page for feeders!?

3) related to the dump1090 instructions
any thought on approximate vs. exact setting?  Is it to keep my location vague?  Or is that plane location?  If it's for me, is that for public listings of where I am? Or just for circles on my screen>

4) Related to MLAT, I was misreading this - On amd64/i386, MLAT is not supported, please answer no.   Being an x64, I should re-run this and say yes?  (and I was seeing in some websites saying it is getting MLAT data from me, which I didn't understand).

5) A big issue - planefinder not getting my data. I go to http://127.0.0.1:30053 and the map shows with no planes. Under log , it keeps restarting, saying that's normal.  I tried 

2020-07-27 16:01:18.421819 [-] TCP connection established: 192.168.19.239:30053
2020-07-27 16:01:18.421605 [-] Client restarted successfully
2020-07-27 16:01:18.421589 [-] Closed TCP connection: 192.168.19.239:30053
2020-07-27 16:01:08.412477 [-] TCP connection established: 192.168.19.239:30053
2020-07-27 16:01:08.412292 [-] Client restarted successfully
2020-07-27 16:01:08.412276 [-] Closed TCP connection: 192.168.19.239:30053
2020-07-27 16:00:58.404500 [-] TCP connection established: 192.168.19.239:30053

stats sent to planefinder is   1,862.984KB (3,106.249KB previously)

but packets are 0.

And the packets per second graph is a dead person : ) 

In settings, i tried the local IP (192.168.19.239), 127.0.0.1 and localhost - all no improvement.

Tcp Address | 192.168.19.239
TCP Port: 30053
Select Timeout 10
data upload interval: 10
connection TCP
aircraft timeout 30
data format: Beast
lat: 40.xxxx
Long: -74...
google maps:   To enable public access to your receiver data you must setup a free Google Maps API key

6) In the instructions for ADSB Exchange you say:

For BEAST/AVR/AVRMLAT, you have a costomized port, use the commands to set.

Are you saying 'IF you have a customized port?'  How would I know?

Or are you saying 'you do have a customized port - (30053), so use the commands to set

I chose the 2nd choice and ran that line with 30053.  ADSB is getting data, so I guess I did that right.

(I do have to go back through understanding that I AM able to do MLAT). 

7) RadarBox: So are you saying that its NOT in the snap?  Or again, since I am running x64, I do have it?  

When I type the commands you list, it says current - inactive (the github page says active.  Is there a command to run to make it active?

david@adsfeeder:~$ snap services adsb-box.rbfeeder
Service                    Startup  Current   Notes
adsb-box.rbfeeder  enabled  inactive  -
david@adsfeeder:~$ adsb-box.rbfeedercli --showkey
+ BIN=/snap/adsb-box/283/usr/bin/rbfeeder
+ '[' '!' -f /snap/adsb-box/283/usr/bin/rbfeeder ']'
+ echo 'The rbfeeder does not exist. Maybe the architecture(amd64) is not supported.'
The rbfeeder does not exist. Maybe the architecture(amd64) is not supported.
+ exit 0
david@adsfeeder:~$ 

Take care!

**Comment by tsunghanliu** [comment]
> I have been looking to set up an ADS-B feeder. I know windows and have a bunch of retired i5 PCs (still quite functional machines). Seemed everyone said I need to buy a Pi to do a feeder.
> 
> Someone in a tech forum turned me on to
> 
> https://snapcraft.io/install/adsb-box/ubuntu
> 
> As a way not to have to buy a Pi which led me to this page.
> 
> THANK YOU FOR DOING THIS!!
> 
> On Friday night I set up an old PC on ubuntu, installed this and started feeding several sites.
> 
> I still have a couple sites that don't seem to be be getting my data. And the github page above has some steps, but i have questions.
> 
> I've never been to github. Is this issues area where people can post questions about configuring things / get help setting things up?

Definitely YES. Issues could be everything related to the project. So, no worries!

> 
> If not, where on the web would you recommend going for support? And or more step-by-step procedures to set things up? Can you tell if lots of people are using this snap?
> 
> An example of my situation - I know ipconfig in windows. In the github page at one point, it says to go to http://your-device-ip:30053/ I didn't know how to get my ip address on a linux box. Googled that ifconfig -a ?! got going to that web page. Just a funny detour.
> 
> Some questions partly about this snap, partly about feeding:
> 
> 1. The processor in this PC is an i5.  But I installed / could only find an AMD64 iso?  And it worked?

Intel i5 CPU is also a kind of amd64. Amd64 is system/CPU architecture and currently the snap supports and64 (64bit x86), i386 (32bit x86), armhf (32bit arm with hard-floating) and arm64 (64bit arm).
 
> 2. What websites is this is setup to feed?
>    I think:
>    Flightaware  (working)
>    FlightRadar24 (working)
>    PlaneFinder (this one isn't getting data into the app itself - see below #5)
>    Radarbox ( this one has errors in terminal - see below #7)
>    ADSBExchange (working)
>    OpenSky (started setting this one up.  But it wants port forwarding to get into the feeder? Gotta set up the rule in my firewall).
> 
> Any others that this snaps ready to talk to? I might as well make sure everyone gets my data?
> 
> Any list of sites and perks you get for feeding? ADSBExchange doesn't even take the ad off their public page for feeders!?

Most of the feeders included in the snap are listed at the [components section](https://github.com/tsunghanliu/adsb-box.snap#components). ADSBExchange doesn't have a feeder, but uses some utilities to forward data to their server.
You can use `snap disable adsb-box.[service_name]` if you don't want to provide your data to particular sites.

> 
> 3. related to the dump1090 instructions
>    any thought on approximate vs. exact setting?  Is it to keep my location vague?  Or is that plane location?  If it's for me, is that for public listings of where I am? Or just for circles on my screen>

This setting only affects the center of circles of theweb pages of dump1090.

> 4. Related to MLAT, I was misreading this - On amd64/i386, MLAT is not supported, please answer no.   Being an x64, I should re-run this and say yes?  (and I was seeing in some websites saying it is getting MLAT data from me, which I didn't understand).

The description is for **fr24feed** only. I think it won't affect the data, but will have some related logs if you have the option enabled. So you can just re-run the config to disable it entirely.

> 5. A big issue - planefinder not getting my data. I go to http://127.0.0.1:30053 and the map shows with no planes. Under log , it keeps restarting, saying that's normal.  I tried
> 
> 2020-07-27 16:01:18.421819 [-] TCP connection established: 192.168.19.239:30053
> 2020-07-27 16:01:18.421605 [-] Client restarted successfully
> 2020-07-27 16:01:18.421589 [-] Closed TCP connection: 192.168.19.239:30053
> 2020-07-27 16:01:08.412477 [-] TCP connection established: 192.168.19.239:30053
> 2020-07-27 16:01:08.412292 [-] Client restarted successfully
> 2020-07-27 16:01:08.412276 [-] Closed TCP connection: 192.168.19.239:30053
> 2020-07-27 16:00:58.404500 [-] TCP connection established: 192.168.19.239:30053
> 
> stats sent to planefinder is 1,862.984KB (3,106.249KB previously)
> 
> but packets are 0.
> 
> And the packets per second graph is a dead person : )
> 
> In settings, i tried the local IP (192.168.19.239), 127.0.0.1 and localhost - all no improvement.
> 
> Tcp Address | 192.168.19.239
> TCP Port: 30053
> Select Timeout 10
> data upload interval: 10
> connection TCP
> aircraft timeout 30
> data format: Beast
> lat: 40.xxxx
> Long: -74...
> google maps: To enable public access to your receiver data you must setup a free Google Maps API key

In the setting page, there are two options `select timeout` and `data upload interval`. If the planefinder client doesn't get any data with the interval, it will restart itself. This is by design. So if your station doesn't have a lot of traffic, you could probably increase the value and see if this improves the restarting. Otherwise it could be something else.

> 
> 6. In the instructions for ADSB Exchange you say:
> 
> For BEAST/AVR/AVRMLAT, you have a costomized port, use the commands to set.
> 
> Are you saying 'IF you have a customized port?' How would I know?
> 
> Or are you saying 'you do have a customized port - (30053), so use the commands to set
> 
> I chose the 2nd choice and ran that line with 30053. ADSB is getting data, so I guess I did that right.
> 
> (I do have to go back through understanding that I AM able to do MLAT).

Sorry, I cannot find the information I read before. And it seems ADS-B Exchange updated the feeder behaviors.
Originally the customized port is at the ADSBExchange server side and is used to identify which user is sending data. So it's optional. You can keep using what you have.

> 
> 7. RadarBox: So are you saying that its NOT in the snap?  Or again, since I am running x64, I do have it?
> 
> When I type the commands you list, it says current - inactive (the github page says active. Is there a command to run to make it active?
> 
> david@adsfeeder:~$ snap services adsb-box.rbfeeder Service            Startup  Current   Notes adsb-box.rbfeeder  enabled  inactive  - david@adsfeeder:~$ adsb-box.rbfeedercli --showkey
> 
> * BIN=/snap/adsb-box/283/usr/bin/rbfeeder
> * '[' '!' -f /snap/adsb-box/283/usr/bin/rbfeeder ']'
> * echo 'The rbfeeder does not exist. Maybe the architecture(amd64) is not supported.'
>   The rbfeeder does not exist. Maybe the architecture(amd64) is not supported.
> * exit 0
>   david@adsfeeder:~$

RadarBox doesn't provide a client application for x86 platforms, so right now for x86, it's just a dummy service to let users know the service is not suitable/available.

> 
> Take care!

Cheers!

**Comment by feetsdr** [comment]
Thank you sooo much!  Lots to look at!  Weird - being home / not commuting, I'd think I'd have loads more time.  But hasn't been the case!

You mention how to disable feeding to certain sites.  Being new to this, I have to ask - why would I want to NOT send to some sites? Just don't like them / their policies?  As a side note, it still feels weird that different sites are each looking to get the same data,  Kinda redundant processes it feels. And for something as important as flight information. I initially thought there was a central organization that collects the data and different websites can get it from that central organization / pot of data.

But no.  Each site collects the same data themselves.  And may not have all the same data.  So users likely will gravitate to the site(s) with the most number of feeders / most complete set of data and the others will shrink.  But since it's pretty easy to feed all the sites, they likely do have pretty similar data...

Please don't mind my ramblings : )
