### ISSUE TITLE
Connection to FlightAware dont work

### ISSUE THREAD

**Issue by LuSou** [tsunghanliu/adsb-box.snap#36]
Hi, 
SkyAware on 192.168.xxx.xxx:8080 worked, but base of piaware status  not running piaware/faup1090/fa-mlat-client/dump1090
and some ERROR exist !!!
Can you help me ?

-------------------
pi@raspberrypi:~ $ adsb-box.piaware-status
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
+ ARCH_TRIPLET=arm-linux-gnueabihf
+ TCL_LIBRARY=/snap/adsb-box/329/usr/share/tcltk/tcl8.6:
+ TCLLIBPATH= /snap/adsb-box/329/usr/share/tcltk/tcl8.6
+ TCLLIBPATH= /snap/adsb-box/329/usr/share/tcltk/tcl8.6 /snap/adsb-box/329/usr/share/tcltk/tcllib1.17
+ TCLLIBPATH= /snap/adsb-box/329/usr/share/tcltk/tcl8.6 /snap/adsb-box/329/usr/share/tcltk/tcllib1.17 /snap/adsb-box/329/usr/share/tcltk/itcl3.4
+ TCLLIBPATH= /snap/adsb-box/329/usr/share/tcltk/tcl8.6 /snap/adsb-box/329/usr/share/tcltk/tcllib1.17 /snap/adsb-box/329/usr/share/tcltk/itcl3.4 /snap/adsb-box/329/usr/share/tcltk/tls1.6.7
+ TCLLIBPATH= /snap/adsb-box/329/usr/share/tcltk/tcl8.6 /snap/adsb-box/329/usr/share/tcltk/tcllib1.17 /snap/adsb-box/329/usr/share/tcltk/itcl3.4 /snap/adsb-box/329/usr/share/tcltk/tls1.6.7 /snap/adsb-box/329/usr/lib/tcltk/arm-linux-gnueabihf/itcl3.4
+ ITCL_LIBRARY=/snap/adsb-box/329/usr/share/tcltk/itcl3.4
+ export TCL_LIBRARY=/snap/adsb-box/329/usr/share/tcltk/tcl8.6:
+ export TCLLIBPATH= /snap/adsb-box/329/usr/share/tcltk/tcl8.6 /snap/adsb-box/329/usr/share/tcltk/tcllib1.17 /snap/adsb-box/329/usr/share/tcltk/itcl3.4 /snap/adsb-box/329/usr/share/tcltk/tls1.6.7 /snap/adsb-box/329/usr/lib/tcltk/arm-linux-gnueabihf/itcl3.4
+ export ITCL_LIBRARY=/snap/adsb-box/329/usr/share/tcltk/itcl3.4
+ /snap/adsb-box/329/usr/bin/piaware-status
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
**PiAware master process (piaware) is not running.
PiAware ADS-B client (faup1090) is not running.
PiAware ADS-B UAT client (faup978) is not running (disabled by configuration settings)
PiAware mlat client (fa-mlat-client) is not running.
Local ADS-B receiver (dump1090) is not running.**

ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
sudo: unable to set runas group vector: Operation not permitted
invalid command name "logger"
    while executing
"logger "failed to run netstat: $result""
    (procedure "inspect_sockets_with_netstat" line 27)
    invoked from within
"inspect_sockets_with_netstat"
    (procedure "netstat_report" line 2)
    invoked from within
"netstat_report"
    (procedure "report_status" line 8)
    invoked from within
"report_status"
    (procedure "main" line 13)
    invoked from within
"main $argv"
    (file "/snap/adsb-box/329/usr/lib/piaware-status/main.tcl" line 42)
    invoked from within
"source /snap/adsb-box/329/usr/lib/piaware-status/main.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 source $path"
    from tcllauncher running "piaware-status"

**Comment by tsunghanliu** [comment]
Hi,

I don't know why your system has `libarmmem-${PLATFORM}.so` defined in `/etc/ld.so.preload`.
I'd suggest that you could comment out the line in `/etc/ld.so.preload`, reboot the system and see if this helps.

Also, do you have the interfaces connected? Please provide `snap connections adsb-box` for debugging.
Here is what a system normally has:

```bash
$ snap connections adsb-box
Interface         Plug                       Slot               Notes
hardware-observe  adsb-box:hardware-observe  :hardware-observe  manual
mount-observe     adsb-box:mount-observe     :mount-observe     manual
network           adsb-box:network           :network           -
network-bind      adsb-box:network-bind      :network-bind      -
network-observe   adsb-box:network-observe   :network-observe   manual
process-control   adsb-box:process-control   :process-control   manual
raw-usb           adsb-box:raw-usb           :raw-usb           manual
system-observe    adsb-box:system-observe    :system-observe    manual
```

**Comment by LuSou** [comment]
new clean installation resolve this ERR.
