### ISSUE TITLE
TAR1090 installation

### ISSUE THREAD

**Issue by LuSou** [tsunghanliu/adsb-box.snap#37]
I would like to install  wiedehopf/tar1090 as this one is better than Piaware.
How to install when dump1090 ... are under snap ?

**Comment by tsunghanliu** [comment]
It's not possible to change the snap or install additional applications over it.
If you are not using Ubuntu Core, you can disable the dump1090 service, install **wiedehopf/tar1090** and configure tar1090 to output BEAST format data to port 30005.

**Comment by LuSou** [comment]
Thks for your Re:
Lubor
