### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by satmandu** [tsunghanliu/adsb-box.snap#50]
I think this just needs to be added to https://github.com/tsunghanliu/adsb-box.snap/blob/master/bin/lighttpd as per https://redmine.lighttpd.net/projects/lighttpd/wiki/IPv6-Config

```
# listen to IPv6
\$SERVER["socket"] == "[::]:$PORT" {  }
```

**Comment by tsunghanliu** [comment]
Hi,

I have updated a version `v1.6.3` to the `candidate` channel. I'll release it to the ``stable` channel next week, if it works correctly and nobody reports issues.

**Comment by satmandu** [comment]
Thanks! It works exactly as expected!
