### ISSUE TITLE
Flightradar24 data sharing software (1.0.25-3)

### ISSUE THREAD

**Issue by dreamworks** [tsunghanliu/adsb-box.snap#59]
Hi guys,

just got the following mail from flightradar24 today.. I assume you're on it?
Thx for your snap! prouldy feeding since more than two years by now...

==
Dear Host, 

We have noticed that you are using an older version of Flightradar24 data sharing software (1.0.25-3) that we are phasing out. We would therefore like you to upgrade to the latest version (1.0.34-0) before Feb 28, 2023.

Follow the procedure given below to upgrade:
1.	SSH into your pi and login to it.
2.	Run the following commands - one at a time:
sudo chmod +x /usr/lib/fr24/fr24feed_updater.sh
sudo /usr/lib/fr24/fr24feed_updater.sh 

If you run into any problems, don’t hesitate to contact us at [support@fr24.com](mailto:support@fr24.com)

**Comment by tsunghanliu** [comment]
Hi @dreamworks 

Thanks for the heads up. I have started working on this and will release a new version soon.

**Comment by tsunghanliu** [comment]
Version 1.6.5 has been released to resolve this issue. If there's any further issue, feel free to reopen this ticket.

**Comment by gompa** [comment]
running snap refresh does not install the fixed version from the store, will this be published to the store or do we need to build from source?

**Comment by tsunghanliu** [comment]
Hi @gompa ,
The new version is available in the store. 
Which architecture and version of adsb-box are you using?
If you are using v1.5.x on i386, that's expected. Because new series of Ubuntu doesn't support i386 anymore. I only build it to include security updates.

**Comment by gompa** [comment]
> Hi @gompa , The new version is available in the store. Which architecture and version of adsb-box are you using? If you are using v1.5.x on i386, that's expected. Because new series of Ubuntu doesn't support i386 anymore. I only build it to include security updates.


you are totally right, it auto updated and the flightradar site took awhile to update the version number shown.
sorry for for any confusion caused
