### ISSUE TITLE
Piaware, fr24 show connection errors, but map working

### ISSUE THREAD

**Issue by satmandu** [tsunghanliu/adsb-box.snap#9]
This is on a ubuntu arm64 box.

```
adsb-box.piaware-status:
+ ARCH_TRIPLET=aarch64-linux-gnu
+ TCL_LIBRARY=/snap/adsb-box/128/usr/share/tcltk/tcl8.6:
+ TCLLIBPATH= /snap/adsb-box/128/usr/share/tcltk/tcl8.6
+ TCLLIBPATH= /snap/adsb-box/128/usr/share/tcltk/tcl8.6 /snap/adsb-box/128/usr/share/tcltk/tcllib1.17
+ TCLLIBPATH= /snap/adsb-box/128/usr/share/tcltk/tcl8.6 /snap/adsb-box/128/usr/share/tcltk/tcllib1.17 /snap/adsb-box/128/usr/share/tcltk/itcl3.4
+ TCLLIBPATH= /snap/adsb-box/128/usr/share/tcltk/tcl8.6 /snap/adsb-box/128/usr/share/tcltk/tcllib1.17 /snap/adsb-box/128/usr/share/tcltk/itcl3.4 /snap/adsb-box/128/usr/share/tcltk/tls1.6.7
+ TCLLIBPATH= /snap/adsb-box/128/usr/share/tcltk/tcl8.6 /snap/adsb-box/128/usr/share/tcltk/tcllib1.17 /snap/adsb-box/128/usr/share/tcltk/itcl3.4 /snap/adsb-box/128/usr/share/tcltk/tls1.6.7 /snap/adsb-box/128/usr/lib/tcltk/aarch64-linux-gnu/itcl3.4
+ ITCL_LIBRARY=/snap/adsb-box/128/usr/share/tcltk/itcl3.4
+ export TCL_LIBRARY=/snap/adsb-box/128/usr/share/tcltk/tcl8.6:
+ export TCLLIBPATH= /snap/adsb-box/128/usr/share/tcltk/tcl8.6 /snap/adsb-box/128/usr/share/tcltk/tcllib1.17 /snap/adsb-box/128/usr/share/tcltk/itcl3.4 /snap/adsb-box/128/usr/share/tcltk/tls1.6.7 /snap/adsb-box/128/usr/lib/tcltk/aarch64-linux-gnu/itcl3.4
+ export ITCL_LIBRARY=/snap/adsb-box/128/usr/share/tcltk/itcl3.4
+ /snap/adsb-box/128/usr/bin/piaware-status
PiAware master process (piaware) is running with pid 1207.
PiAware master process (piaware) is running with pid 1769.
PiAware ADS-B client (faup1090) is running with pid 2093.
PiAware ADS-B UAT client (faup978) is not running.
PiAware mlat client (fa-mlat-client) is not running.
Local ADS-B receiver (dump1090) is running with pid 1206.
Local ADS-B receiver (dump1090-fa) is running with pid 1675.

unknown process (pid unknown) is listening for connections on port 30005.
no program appears to be listening for connections on port 30978.

got 'couldn't open socket: connection refused'
dump1090 is producing data on localhost:30005.

You don't have a feeder ID yet.
```
```
adsb-box.fr24feed-status
FR24 Feeder/Decoder Process is running
FR24 Stats Timestamp: 2019-07-04 17:36:17
FR24 Link: connected [UDP]
FR24 Radar: T-KPWM1
FR24 Tracked AC: 0
Receiver: down
```

**Comment by tsunghanliu** [comment]
Are you talking about this error?

> got 'couldn't open socket: connection refused'

It's because there is no dump978 existing/running in this snap.
At this moment, I'm still thinking about including dump978 is good or not. According to [this article](https://cincinnatiavionics.com/ads-b-out-difference-1090-978/) and what I've read, it seems dump978 (UAT 978MHz) only working in US. For other countries, UAT is not used.

**Comment by satmandu** [comment]
Thanks for the clarification. 

But I think there is another problem, since while I am seeing traffic in the web map, I am not seeing any traffic being uploaded to flightaware or fr24.

Maybe the output above says that too?

**Comment by tsunghanliu** [comment]
Oh, sorry, I didn't notice that your fr24feed-status also said:
> Receiver: down

Let's collect more information and see if there's any clue.
1. **PiAware**: on https://flightaware.com/adsb/stats/user/_YOUR_FLIGHTAWARE_ID_, can you see your feeder? I remember that you should [claim](https://flightaware.com/adsb/piaware/claim) (see section 5th of this [page](https://flightaware.com/adsb/piaware/build)) the feeder before seeing its data
2. **FR24**: on https://www.flightradar24.com/account/data-sharing, does it show any error in _Status_ and _Statistics_?
3. Could you please upload the logs? The logs would be truncated and you probably have to restart the services before collect the logs 
```sh
# to restart services
$ snap restart adsb-box.piaware
$ snap restart adsb-box.fr24feed
# wait a few minutes

# to collect logs
$ snap logs adsb-box.piaware -n all
$ snap logs adsb-box.fr24feed -n all
```

**Comment by satmandu** [comment]
1. **PiAware**: Yes the feeder shows as claimed. (Also got the "Welcome! PiAware 'site UUID' is activated and now live on FlightAware!" email.)
2. **FR24**: No errors. Just no data uploaded.

Logs:
**PiAware**: https://paste.ubuntu.com/p/c4Vr4wspRb/
**FR24**: https://paste.ubuntu.com/p/3Z3qnPP8gZ/

**Comment by tsunghanliu** [comment]
Thanks for the logs.

1. **PiAware**: from the log, I can see the [statistics](https://flightaware.com/adsb/stats/user/satadru1#stats-106445) of your feeder. Isn't it correct now?
2. **FR24**: it seems the configuration of receiver is incorrect. Are you using configurations from other/previous feeder? What I'm using on my feeder: `receiver="beast-tcp"` (ModeS Beast (TCP)) and `host="localhost:30005"`. You can check `/var/snap/adsb-box/current/fr24feed/fr24feed.ini` or `http://your_feeder_ip:8754/settings.html` (this is provided by fr24feed).
> [reader][e]Could not connect to avr-tcp://127.0.0.1:30002

**Comment by satmandu** [comment]
1. **!** I hadn't realized that flightaware was showing two sites!  Thanks for the feedback. I've fixed the UUID in the feeder_id file so that is fixed.
2. Yes it appears that I had fr24 misconfigured. I think I fixed it by editing the config file directly.

FYI when trying to run ```sudo adsb-box.fr24feedcli --reconfigure``` I get stuck at this step:

```
Step 6B - Please enter desired logfile path (/var/log/fr24feed):
$:/var/log/fr24feed
Path /var/log/fr24feed is not accessible, please enter correct log path!
```
(Nothing entered here seems to work - and it doesn't seem to be ok with $SNAP variables.)


Otherwise I'm all set!

**Comment by punnerud** [comment]
First run this to update locate
`sudo updatedb`
Check if you have a fr24feed.ini file
`locate fr24feed.ini`
The default if is location is /etc/fr24feed.ini

This is my content for fr24feed.ini to make it work with DUMP1090
```
receiver="avr-tcp"
host="localhost:30002"
bs="no"
raw="no"
logmode="2"
windowmode="0"
mlat="yes"
mlat-without-gps="yes"
```
